name = "CLFFT"
uuid = "fe1fc2a7-b730-4eae-aba2-587af0173dc9"
authors = ["jakebolewski <jakebolewski@gmail.com>"]
version = "0.2.0"

[deps]
CLFFT_jll = "3d56f106-398e-55cb-9b6b-0dced46c254c"
OpenCL = "08131aa3-fb12-5dee-8b74-c09406e224a2"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
OpenCL = "0.9.0"